title: "HPC Resource Management Team"
name: "HPC Resource Management Team"
description: "Official website of our research group"

url: "https://cslab-ntua.github.io"   # the main org GitHub Pages URL
baseurl: "/hpc_resource_management"              # the repo name

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

# Site settings
minimal_mistakes_skin: "default"

# Navigation
collections:
  team:
    output: true
  research:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: research
    values:
      layout: single
  - scope:
      path: ""
      type: team
    values:
      layout: single
  - scope:
      path: ""
      type: projects
    values:
      layout: single
